language: python
python:
        -3.7.4
before_install:
        -python --version
        -pip install -U pip
        -pip install codecov
script:
        -coverage run --source=com/jefferson/ -m unittest discover;coverage report -m
        -python -m unittest discover
